apiVersion: v1
kind: Service
metadata:
  name: cloud-native-mini-service
  namespace: cloud-mini
  labels:
    app: cloud-native-mini

spec:
  selector:
    app: cloud-native-mini

  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000

  type: ClusterIP
